Заглушка к ПЗ ко 2му вебинару

## Линейная алгебра. Вебинар 2. Урок 3. Практическое задание

In [1]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


__Решение:__

а) АВ и ВА не определены, т.к. число столбцов первой матрицы не равно числу строк второй в обоих вариантах;<br>
б) АВ определено, размерность полученной матрицы $2\times 3$ ; BA  не определено;<br>
в) АВ определено, размерность полученной матрицы $8\times 8$ ; ВА определено, размерность полученной матрицы $3\times 3$ ;<br>
в) АВ и BA определены, размерность полученных матриц $4\times 4$.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


__Решение:__

$A + В = \begin{pmatrix}
1 + 4 & -2 - 1\\ 
3 + 0 & 0 + 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$;



$A \cdot В = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1\cdot4+{(-2)}\cdot 0 & 1\cdot{(-1)}+{(-2)}\cdot5\\ 
3\cdot4 + 0\cdot0 & 3\cdot{(-1)}+ 0\cdot5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$;<br>


In [2]:
A = np.array([[1, -2],
              [3, 0]])

B = np.array([[4, -1],
              [0, 5]])
print(f'A+B = \n{A+B}\n')
print(f'A*B = \n{A@B}')

A+B = 
[[ 5 -3]
 [ 3  5]]

A*B = 
[[  4 -11]
 [ 12  -3]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение:__

$3A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$, $-2B=\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}$, $4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}.$<br>

$3A-2B+4C = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [3]:
A = np.array([[1, 7],
              [3, -6]])

B = np.array([[0, 5],
              [2, -1]])

C = np.array([[2, -4],
              [1, 1]])

print(f'3A-2B+4C = \n{3*A-2*B+4*C}\n')

3A-2B+4C = 
[[ 11  -5]
 [  9 -12]]



    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


__Решение:__

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$

$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} = \begin{pmatrix}
4\cdot4 + 1\cdot1 & 4\cdot5+1\cdot{(-2)} & 4\cdot2 + 1\cdot3\\ 
5\cdot4 + (-2)\cdot1 & 5\cdot5+(-2)\cdot{(-2)} & 5\cdot2 + (-2)\cdot3\\ 
2\cdot4 + 3\cdot1 & 2\cdot5+3\cdot{(-2)} & 2\cdot2 + 3\cdot3\\ 
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 &  4\\ 
11 &  4 & 13\\ 
\end{pmatrix}$

$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4 + 5\cdot5 + 2\cdot2 & 4\cdot1 + 5\cdot{(-2)} + 2\cdot3\\ 
1\cdot4 + (-2)\cdot5 + 3\cdot2 & 1\cdot1+(-2)\cdot{(-2)} + 3\cdot3\\ 
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14\\ 
\end{pmatrix}$

In [4]:
A = np.array([[4, 1],
              [5, -2],
              [2, 3]])

A@A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [5]:
A.T@A

array([[45,  0],
       [ 0, 14]])


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [6]:

def msize(mx):
    sz = [len(mx)]
    col = len(mx[0])
    for i, el in enumerate(mx):
        if len(el) != col:
            print(f'В 1й строке матрицы {col} значений, а в {i+1}й - {len(el)}, должно быть одинаково!')
            exit()
    sz.append(col)
    return tuple(sz)


def mdot(a, b):
    asize = msize(a)
    bsize = msize(b)
    if asize[1] == bsize[0]:
        result = []
        bt = list(map(list, zip(*b))) # [[1, 4, 5], [2, 5, 7], [3, 6, 9], [4, 8, 3]]
        for s in a:
            dotstr = []
            for st in bt:                               # [[1, 2, 3], [4, 5, 6]]
                dotstr.append(sum([s[i] * st[i] for i in range(len(s))]))
            result.append(dotstr)

        return result
    else:
        print(f'Количество столбцов в матрице А ({asize[1]})'
              f' не равно количеству строк в В ({bsize[0]}), операция умножения невозможна')


A = [[1, 2, 3],
     [4, 5, 6]]

B = [[1, 2, 3, 4],
     [4, 5, 6, 8],
     [5, 7, 9, 3]]

# [[24, 33, 42, 29],
#  [54, 75, 96, 74]]

print(msize(A))
print(msize(B))
# print(msize([[1,2],[3]]))

print(mdot(A, B))


(2, 3)
(3, 4)
[[24, 33, 42, 29], [54, 75, 96, 74]]


In [7]:
# Проверка:

A = np.array(A)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
B = np.array(B)
B

array([[1, 2, 3, 4],
       [4, 5, 6, 8],
       [5, 7, 9, 3]])

In [9]:
A@B

array([[24, 33, 42, 29],
       [54, 75, 96, 74]])

## Линейная алгебра. Вебинар 2. Урок 4. Практическое задание

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$


$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^2 x - (- cos^2 x) = 1$$


$$A_{ij}=(-1)^{i+j}M_{ij}.$$

Найдем алгебраические дополнения для каждого элемента:

$$A_{11}=(-1)^{2}\begin{vmatrix}
sinx
\end{vmatrix} = sinx,~
A_{12}=(-1)^{3}\begin{vmatrix}
cosx
\end{vmatrix} = -cosx,$$
$$A_{21}=(-1)^{3}\begin{vmatrix}
-cosx
\end{vmatrix} = cosx,~
A_{22}=(-1)^{4}\begin{vmatrix}
sinx
\end{vmatrix} = sinx.$$

Полученная матрица из алгебраических дополнений:

$$A^{*} = \begin{pmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{pmatrix},~
A^{*T} = \begin{pmatrix}
sinx & cosx\\ 
-cosx & sinx
\end{pmatrix}.$$

Используя формулу из алгоритма, получим

$$A^{-1} = \frac{1}{1}\cdot \begin{pmatrix}
sinx & cosx\\ 
-cosx & sinx
\end{pmatrix} = \begin{pmatrix}
sinx & cosx\\ 
-cosx & sinx
\end{pmatrix}.$$

$$A^{(-1)} = A^T$$


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} =4\cdot5\cdot9=180.$$
    


In [10]:
np.linalg.det(np.array([[4,2,3],
                        [0,5,1],
                        [0,0,9]
                       ]))

180.0

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = \begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = \begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{vmatrix} = 0.$$



In [12]:
np.linalg.det(np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9]
                       ]))

-9.51619735392994e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = det( A \cdot A) = det(A) \cdot det(A) = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = 2 \cdot det(A) = 8$.
   


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


Прибавим ко 2й строке первую, умноженную на 2:$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = \begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{vmatrix}
$$
Определитель матрицы с 0 строкой = 0

In [17]:
np.linalg.det(np.array([[-2,7,-3],
                        [4,-14,6],
                        [-3,7,13]
                       ]))

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$


Третью строку отбрасываем, т.к. она равна сумме двух первых. Вычтем из второй строки первую:

$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix};$

Т.о. ранг матрицы равен 2


In [16]:
np.linalg.matrix_rank([[1,2,3],
                       [1,1,1],
                       [2,3,4]
                       ])

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Отбросим 3 строку, т.к. она является суммой двух первых. Отбросим 2 столбец как линейно зависимый от 1го.

$\begin{pmatrix}
0 & 2 & 1\\ 
0 & 2 & 2\\ 
2 & 5 & 6
\end{pmatrix};$

Прибавим к 1 столбцу третий, помноженный на -1/3:

$\begin{pmatrix}
-1/3 & 2 & 1\\ 
-2/3 & 2 & 2\\ 
0 & 5 & 6
\end{pmatrix};$

Прибавим ко 2 столбцу третий, помноженный на -5/6:

$\begin{pmatrix}
-1/3 & 7/6 & 1\\ 
-2/3 & 2/6 & 2\\ 
0 & 0 & 6
\end{pmatrix};$

Прибавим ко 2 строке 1ю , помноженную на -2:

$\begin{pmatrix}
-1/3 & 7/6 & 1\\ 
0 & -2 & 0\\ 
0 & 0 & 6
\end{pmatrix};$

Итак, ранг матрицы равен 3.


In [18]:
np.linalg.matrix_rank([[0,0,2,1],
                       [0,0,2,2],
                       [0,0,4,3],
                       [2,3,5,6],
                       ])

3