In [1]:
import numpy as np

## Практическое задание к вебинару 3 Линейная алгебра

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$


__Решение:__

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)-(-6)\cdot2=0,$$

$$-6+\lambda-6\lambda + \lambda^2+12=0,$$

$$\lambda^2-5\lambda+6=0,$$

$$D=(-5)^2-4\cdot1\cdot6=1,$$

$$\lambda=(-(-5)\pm\sqrt1)\div(2\cdot1)=(3,  2).$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Для $\lambda = 3$ получим

$$\begin{cases}
-x_{1}-6x_{2}= 3x_{1}, \\
2x_{1}+6x_{2}= 3x_{2}.
\end{cases}$$ 

Перенеся все в левую часть, получим

$$\begin{cases}
-4x_{1}-6x_{2} = 0, \\
2x_{1}+3x_{2} = 0;
\end{cases}$$ 

$$x_{1}=-1.5x_{2}$$

In [9]:
A = np.array([[-1,-6],
              [ 2, 6]])
B = np.array([[-3], # один из вариантов собственного вектора при lambda=3
              [2]])
lmbd = 3

print(A@B)
print(lmbd*B)

print(A@B == lmbd*B)

[[-9]
 [ 6]]
[[-9]
 [ 6]]
[[ True]
 [ True]]


Для $\lambda = 2$ получим

$$\begin{cases}
-x_{1}-6x_{2}= 2x_{1}, \\
2x_{1}+6x_{2}= 2x_{2}.
\end{cases}$$ 

Перенеся все в левую часть, получим

$$\begin{cases}
-3x_{1}-6x_{2} = 0, \\
2x_{1}+4x_{2} = 0;
\end{cases}$$ 

$$x_{1}=-2x_{2}$$

In [10]:
A = np.array([[-1,-6],
              [ 2, 6]])
B = np.array([[-4], # один из вариантов собственного вектора при lambda=3
              [2]])
lmbd = 2

print(A@B)
print(lmbd*B)

print(A@B == lmbd*B)

[[-8]
 [ 4]]
[[-8]
 [ 4]]
[[ True]
 [ True]]


In [3]:
a = np.array([[-1,-6],
              [ 2, 6]])

w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]



__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.



__Решения:__

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)^2-0\cdot0=0,$$

$$-1-\lambda=0,$$

$$\lambda=-1$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Для $\lambda = -1$ получим

$$\begin{cases}
-x_{1}+0\cdot{x_{2}}= -x_{1}, \\
0\cdot{x_{1}}+(-1)x_{2}= -x_{2}.
\end{cases}$$ 

$$\begin{cases}
-x_{1}= -x_{1}, \\
-x_{2}= -x_{2}.
\end{cases}$$ 


или

$$\begin{cases}
x_{1}= x_{1}, \\
x_{2}= x_{2}.
\end{cases}$$ 

Что верно для любого вектора, ч.т.д.

In [11]:
a = np.array([[-1,0],
              [ 0, -1]])

w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



__Решение:__
Проверим выражение, которое должно соблюдаться для собственных векторов $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$,  $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\begin{pmatrix}
1\cdot1 + 1\cdot1\\ 
-1\cdot1 + 3\cdot1
\end{pmatrix}=
\begin{pmatrix}
2\\ 
2
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix} при \lambda = 2.
$$

In [13]:
a = np.array([[ 1, 1],
              [-1, 3]])

w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')
print(a@np.array([[1],
                  [1]]))

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]
[[2]
 [2]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение:__
Проверим выражение, которое должно соблюдаться для собственных векторов $\begin{pmatrix}
x_{1}\\ 
x_{2}\\
x_{3}
\end{pmatrix}$,  $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\ 
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\ 
-4
\end{pmatrix}=
\begin{pmatrix}
0\cdot3 + 3\cdot{(-3)} + 0\cdot{(-4)}\\ 
3\cdot3 + 0\cdot{(-3)} + 0\cdot{(-4)}\\ 
0\cdot3 + 0\cdot{(-3)} + 3\cdot{(-4)}
\end{pmatrix}=
\begin{pmatrix}
-9\\ 
9\\ 
-12
\end{pmatrix}<>
\lambda
\begin{pmatrix}
3\\ 
-3\\ 
-4
\end{pmatrix}
$$
Равенство  не  существует, т.е. вектор $x=(3, -3, -4)$ не является собственным вектором. 


In [14]:
a = np.array([[0, 3, 0],
              [3, 0, 0],
              [0, 0, 3]])

w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')
print(a@np.array([[3],
                  [-3],
                  [-4]]))

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[[ -9]
 [  9]
 [-12]]
