## ПЗ к 4 вебинару Линейной алгебры (уроки 6 и 7).

In [1]:
import numpy as np

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$


__Решение:__

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из 2 строки первую, умноженнную на 2; вычтем из 3 строки первую.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Оставшаяся матрица соответствует системе

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2х_{4}=0, \\
~~~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~~~~~~~~~-2x_{3}+3x_{4}=4.
\end{cases}$$

_Общее решение_:

_Свободный_ параметр $x_{4}=c$

$$x_{3}=1.5c-2,$$
$$-x_{2}+1.5c-2+5c=-2 \; \Leftrightarrow \; x_{2}=6.5с,$$
$$x_{1}+6.5с-(1.5с-2)-2c=0 \; \Leftrightarrow \; x_{1}=-3с-2.$$




__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$


__Решение__

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3\\ 
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$

n = 3. Определяем ранг матрицы:

Меняем местами 1 и 3 строки:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\ 
2 & -5 & -3\\ 
3 & -1 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-17\\
4
\end{matrix}
\end{pmatrix}$$

вычитаем из 2 строки 1ю, умноженную на 2, и из 3 строки 1ю, умноженную на 3:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\ 
0 & -7 & -1\\ 
0 & -4 & 4
\end{matrix}\right|
\begin{matrix}
0\\ 
-17\\
4
\end{matrix}
\end{pmatrix}$$

умножим 2 строку на -4, 3ю на 7 и прибавим к 3й строке 2ю:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\ 
0 & 28 & 4\\ 
0 & 0 & 32
\end{matrix}\right|
\begin{matrix}
0\\ 
68\\
96
\end{matrix}
\end{pmatrix}$$

$rankA=rank \tilde A=n = 3$.<br>
__Система совместна и определена (имеет единственное решение).__

In [12]:
A = np.array([[3,-1,1],
              [2,-5,-3],
              [1,1,-1]])

Ae = np.array([[3,-1,1,4],
              [2,-5,-3,-17],
              [1,1,-1,0]])

print(f'Rank A = {np.linalg.matrix_rank(A)}, rank A extended = {np.linalg.matrix_rank(Ae)}')



Rank A = 3, rank A extended = 3


    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$


__Решение__

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6\\ 
1 & -2 & 3\\ 
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$

n = 3. Определяем ранг матрицы:

Меняем местами 1 и 2 строки:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3\\ 
2 & -4 & 6\\ 
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
-2\\
1\\ 
5
\end{matrix}
\end{pmatrix}$$

вычитаем из 2 строки 1ю, умноженную на 2, и из 3 строки 1ю, умноженную на 3:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3\\ 
0 & 0 & 0\\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
-2\\
5\\ 
11
\end{matrix}
\end{pmatrix}$$


$rankA=1, rank \tilde A=2, n = 3$.<br>
__Система несовместна и не имеет решения).__

In [13]:
A = np.array([[2,-4,6],
              [1,-2,3],
              [3,-6,9]])

Ae = np.array([[2,-4,6,1],
              [1,-2,3,-2],
              [3,-6,9,5]])

print(f'Rank A = {np.linalg.matrix_rank(A)}, rank A extended = {np.linalg.matrix_rank(Ae)}')



Rank A = 1, rank A extended = 2


    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$



__Решение__

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
3 & 1 & -8 
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$$

n = 3. Определяем ранг матрицы:

Вычитаем из 2 строки 1ю, умноженную на 3:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
0 & -5 & -23 
\end{matrix}\right|
\begin{matrix}
4\\ 
-14
\end{matrix}
\end{pmatrix}$$

$rankA=rank \tilde A=2, n = 3$.<br>
__Система совместна и неопределена (имеет бесконечное множество решений).__

In [14]:
A = np.array([[1,2,5],
              [3,1,-8]])

Ae = np.array([[1,2,5,4],
               [3,1,-8,-2]])

print(f'Rank A = {np.linalg.matrix_rank(A)}, rank A extended = {np.linalg.matrix_rank(Ae)}')



Rank A = 2, rank A extended = 2



__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__Решение:__
$rankA=rank \tilde A=n = 4$.<br>
__Система совместна и определена (имеет единственное решение).__

In [15]:
A = np.array([[1,3,-2,4],
               [0,5,0,1],
               [0,0,3,0],
               [0,0,0,2]])

Ae = np.array([[1,3,-2,4,3],
               [0,5,0,1,2],
               [0,0,3,0,4],
               [0,0,0,2,1]])

print(f'Rank A = {np.linalg.matrix_rank(A)}, rank A extended = {np.linalg.matrix_rank(Ae)}')



Rank A = 4, rank A extended = 4



__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение:__

Если $rankA<rank \tilde A$, то система несовместна.

n = 3. Определяем ранг матрицы:

Вычитаем из 2 строки первую, умноженную на 4, и изп 3 строки 1ю, умноженную на 7:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12 
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\ 
c-7a
\end{matrix}
\end{pmatrix}$$

Прибавляем к 3 строке 2ю, умноженную на 2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\ 
c-7a + 2b - 8a
\end{matrix}
\end{pmatrix}$$


$rankA=2, rank \tilde A>2$ при условии что с+2b-15a <> 0, т.е. соотношение должно быть:<br>
__Ответ: с+2b <> 15a__<br>

## Практическое задание ч.2 (Урок 7)

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

Программа решения СЛАУ методом Крамера:

In [97]:
def kram(A, b):
    detA = np.linalg.det(A)
    print(f'Определитель матрицы А: detA = {detA:.2g}\n\n')
    xvec = np.array([0]) # [0] добавил для корректной работы функции vstack ниже
    for i in range(A.shape[1]):
        Ai = A.copy()
        Ai[:,i] = b.flatten()
        print(f'{i+1}я матрица замены: \n{Ai}\n')
        detAi = np.linalg.det(Ai)
        print(f'Определитель detA{i+1} = {detAi:.2g}\n')
        x = np.array([detAi/detA])
        print(f'x{i+1} = {x[0]:.2g}\n')
        xvec = np.vstack((xvec, x))
    
    
    return xvec[1:] # без 1й ненужной строки [0]

In [98]:
A = np.array([[1,-2],
              [3,-4]])
b = np.array([[1],
              [7]])
xall = kram(A,b)
xall

Определитель матрицы А: detA = 2


1я матрица замены: 
[[ 1 -2]
 [ 7 -4]]

Определитель detA1 = 10

x1 = 5

2я матрица замены: 
[[1 1]
 [3 7]]

Определитель detA2 = 4

x2 = 2



array([[5.],
       [2.]])

In [99]:
A@xall

array([[1.],
       [7.]])

    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


In [100]:
A = np.array([[2,-1,5],
              [1,1,-3],
              [2,4,1]])
b = np.array([[10],
              [-2],
              [1]])
xall = kram(A,b)
xall

Определитель матрицы А: detA = 43


1я матрица замены: 
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]

Определитель detA1 = 86

x1 = 2

2я матрица замены: 
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]

Определитель detA2 = -43

x2 = -1

3я матрица замены: 
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]

Определитель detA3 = 43

x3 = 1



array([[ 2.],
       [-1.],
       [ 1.]])

In [78]:
A@xall

array([[10.],
       [-2.],
       [ 1.]])

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$


__Решение__:

Домножим 1 строку на 2 и вычтем ее из 2й; домножим 1 строку на 3 и вычтем ее из 3. Матрица коэффициентов будет иметь вид:

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}.$$


Далее умножим вторую строку на $(4)$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

В итоге получим

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$


In [103]:
U = np.array([[1,2,4],
              [0,5,4],
              [0,0,2]])
L = np.array([[1,0,0],
              [2,1,0],
              [3,4,1]])
L@U

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$


__Решение__:

Домножим 1 строку на 2 и вычтем ее из 2й; домножим 1 строку на 3 и вычтем ее из 3, домножим 1 на 4 и вычтем из 4й. Матрица коэффициентов будет иметь вид:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & l_{32} & 1 & 0 \\
4 & l_{42} & l_{43} & 1
\end{pmatrix}.$$


Далее умножим вторую строку на $(5)$ и вычтем ее из третьей, и, умножив ее же на 6 - вычтем из четвертой:

Получим

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$

$$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & l_{43} & 1
\end{pmatrix}.$$


Далее умножим третью строку на $(7)$ и вычтем ее из четвертой:

Получим $U$ - 

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}.$$


In [104]:
U = np.array([[1,1,2,4],
              [0,3,4,1],
              [0,0,3,1],
              [0,0,0,4]])
L = np.array([[1,0,0,0],
              [2,1,0,0],
              [3,5,1,0],
              [4,6,7,1]])
L@U

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

    
__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$


Матрица коэффициентов $A$ будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}.$$

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $11/2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $11/2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $9/2$. Значит, в матрицу $L$ запишем $l_{31}=9/2$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 7/2 & -19/2
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $(7/3)$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $7/3$.

В итоге получим

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 0 & 52/3
\end{pmatrix},$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & 7/3 & 1
\end{pmatrix}.$$

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
(11/2)y_{1}+y_{2}=-6, \\
(9/2)y_{1}+(7/3)y_{2}+y_{3}=-5.
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-23/2,$$
$$y_{3}=52/3.$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
(3/2)x_{2}-(23/2)x_{3}=-23/2, \\
(52/3)x_{3}=52/3.
\end{cases}$$

$$x_{3}=1,$$
$$x_{2}=0,$$
$$x_{1}=-1.$$

Произведем проверку, подставив полученные значения переменных в исходную систему:

$$\begin{cases}
2\cdot{(-1)}+1\cdot0+3\cdot1=1 \\
11\cdot{(-1)}+7\cdot0+5\cdot1=-6 \\
9\cdot{(-1)}+8\cdot0+4\cdot1=-5
\end{cases}$$

Таким образом, найденное решение верно.

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$


Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$


Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
(-5)y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=\frac{-460+5\cdot59}{5}=-33,$$

$$y_{3}=\frac{193-5\cdot59-2\cdot{(-33)}}{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=\frac{-33-2\cdot{(-4)}}{5}=-5,$$

$$x_{1}=\frac{59+5\cdot{(-5)}-5\cdot{(-4)}}{9}=6.$$

Осуществим проверку, подставив полученные значения в исходную систему:

$$\begin{cases}
81\cdot6-45\cdot{(-5)}+45\cdot{(-4)}=531 \\
-45\cdot6+50\cdot{(-5)}-15\cdot{(-4)}=-460 \\
45\cdot6-15\cdot{(-5)}+38\cdot{(-4)}=193
\end{cases}$$

решение задачи 5 выше